import type { Metadata } from 'next'
import './globals.css'
import Navbar from './nav/Navbar'
import ToasterProvide from './providers/ToasterProvide'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <ToasterProvide />
        <Navbar />
        <main className='container mx-auto pt-10'>
          {children}
        </main>
      </body>
    </html>
  )
}
